server:
  port: 8088

spring:
  output:
    ansi.enabled: always
  messages:
    basename: messages
    fallback-to-system-locale: false
  security:
    user:
      name: megasoby
      password: passw0rd

logging:
  level:
    org.springframework: DEBUG





